Python numerical types
featuremine/extractor pull request #27
Opened 2022-11-07 21:45 UTC by fm-andres-rangel

2022-11-09 17:11 UTC, fm-ivang requested changes

2022-11-09 17:11 UTC, fm-ivang commented on python/py_rational64.hpp
> +  return PyLong_FromLong(llround(dest));
FromLongLong

2022-11-09 17:11 UTC, fm-ivang commented on python/py_rprice.hpp
> +  return PyLong_FromLong(dest);
FromLongLong

2022-11-09 17:11 UTC, fm-ivang commented on test/numerical.py
> +    assert float(v1) == 2.34375
Add test for overflow

2022-11-14 20:22 UTC, fm-ivang approved these changes

2022-11-14 21:26 UTC, maxim-trokhimtchouk approved these changes

2022-11-15 14:56 UTC, maxim-trokhimtchouk approved these changes

2022-11-15 15:02 UTC, merged