Fix wheel include dir
featuremine/extractor pull request #28
Opened 2022-11-08 21:06 UTC by fm-ivang

2022-11-08 21:10 UTC, fm-andres-rangel submitted a review, later dismissed

2022-11-08 21:18 UTC, maxim-trokhimtchouk approved these changes

2022-11-08 21:21 UTC, fm-andres-rangel requested changes

2022-11-08 21:21 UTC, fm-andres-rangel commented on setup.py
> +        'extractor': ['extractor.so', 'libextractor*', 'include', 'include/*', 'include/*/*', 'include/*/*/*']
add the license so setup.py can add it to the wheel

2022-11-09 13:38 UTC, fm-andres-rangel approved these changes

2022-11-09 13:39 UTC, merged