Directories improvement
featuremine/extractor pull request #49
Opened 2022-12-01 21:43 UTC by fm-ivang

2022-12-22 17:41 UTC, fm-fede-ravchina approved these changes

2023-01-03 15:21 UTC, fm-andres-rangel requested changes

2023-01-03 15:21 UTC, fm-andres-rangel commented on python/setup.py
>  import sys
The copyright notices seem irregular, looks like some of them have different years and the LICENSE file in the main directory uses Featuremine LLC instead of Featuremine Corporation

2023-01-05 14:52 UTC, fm-fede-ravchina commented on python/setup.py
> +extractor_version = list(open(path.join(path.dirname(__file__), '..', 'VERSION')))[0].strip()
Tecnically they don't necessarily return the same path:
```
os.path.dirname('/root/.config/..') = ''/root/.config'
os.path.join('/root/.config/..', '..') = '/root/.config/../..'
```

dirname does not necessarily return the upperlevel directory

2023-01-05 15:20 UTC, fm-andres-rangel commented on CMakeLists.txt
> +set(WHEEL_extractor_BUILD_DIR "${CMAKE_CURRENT_BINARY_DIR}/python")
understood

2023-01-05 15:42 UTC, fm-andres-rangel approved these changes

2023-01-05 19:47 UTC, maxim-trokhimtchouk approved these changes

2023-01-05 19:47 UTC, merged