Join operator fixes
featuremine/extractor pull request #73
Opened 2023-04-12 19:17 UTC by fm-andres-rangel

2023-04-12 19:35 UTC, fm-fede-ravchina approved these changes

2023-04-12 19:50 UTC, fm-fede-ravchina approved these changes

2023-04-12 23:44 UTC, maxim-trokhimtchouk submitted a review, later dismissed

2023-04-13 22:15 UTC, fm-fede-ravchina requested changes

2023-04-13 22:15 UTC, fm-fede-ravchina commented on CMakeLists.txt
> +    TARGETS fmc++ ytp py_yamal_dep yamal-whl WHEEL_yamal_BUILD_DIR
WHEEL_yamal_BUILD_DIR is not a target, it's just a global variable. We should remove it

2023-04-13 22:15 UTC, fm-fede-ravchina commented on python/CMakeLists.txt
> +            endif()
indentation is incorrect

2023-04-14 14:03 UTC, fm-fede-ravchina submitted a review, later dismissed

2023-04-14 19:42 UTC, maxim-trokhimtchouk approved these changes

2023-04-14 19:46 UTC, fm-fede-ravchina approved these changes

2023-04-14 20:01 UTC, merged