Extension api improvements
featuremine/extractor pull request #89
Opened 2023-09-01 13:40 UTC by fm-andres-rangel

2023-09-01 15:59 UTC, maxim-trokhimtchouk requested changes

2023-09-01 15:59 UTC, maxim-trokhimtchouk commented on api/include/extractor/api.h
> +  void (*module_type_add)(struct fm_comp_sys_module *mod,
Doesn't make sense

2023-09-01 15:59 UTC, maxim-trokhimtchouk commented on api/include/extractor/api.h
> +                               const fm_comp_def_t *def, fmc_error_t **error);
Doesn't make sense either

2023-09-01 15:59 UTC, maxim-trokhimtchouk commented on include/extractor/comp_sys.h
> +FMMODFUNC void fm_comp_sys_paths_set_default(struct fm_comp_sys *sys,
need the default one

2023-09-01 15:59 UTC, maxim-trokhimtchouk commented on python/src/sys_def.hpp
> +    fmc_error_t *error;
No lazy system creation. Just create one in the extractor module

2023-09-01 15:59 UTC, maxim-trokhimtchouk commented on api/include/extractor/api.h
> +typedef void (*fm_comp_sys_module_init_func)(struct extractor_api_v1 *,
should be fm_comp_sys_module_init_v1

2023-09-01 15:59 UTC, maxim-trokhimtchouk commented on api/include/extractor/api.h
> +                                             struct fm_comp_sys_module *,
fm_comp_sys_t *

2023-09-06 18:54 UTC, maxim-trokhimtchouk commented on python/src/sys_def.hpp
> +  for (auto &&comp : self->custom) {
can be removed

2023-09-06 18:54 UTC, maxim-trokhimtchouk approved these changes

2023-09-06 19:00 UTC, maxim-trokhimtchouk approved these changes

2023-09-06 19:49 UTC, fm-fede-ravchina approved these changes

2023-09-06 19:49 UTC, fm-fede-ravchina commented on test/ext_exe.cpp
> +}
end of line is missing

2023-09-06 19:49 UTC, fm-fede-ravchina commented on src/comp_sys.cpp
> +mod_load(struct fm_comp_sys *sys, const char *dir, const char *modstr,
shouldn't we reuse extension.h implementation, just like conveyor market data extension does? This logic was copied from yamal before we decided to separate the generic extension logic from the component API

2023-09-06 19:51 UTC, fm-fede-ravchina requested changes
I've missclicked approve

2023-09-06 22:45 UTC, maxim-trokhimtchouk approved these changes

2023-09-06 22:46 UTC, maxim-trokhimtchouk commented on src/comp_sys.cpp
> +mod_load(struct fm_comp_sys *sys, const char *dir, const char *modstr,
Yes, we should. I was confused. I thought that you discussed this with Andres.

2023-09-07 13:49 UTC, fm-fede-ravchina approved these changes

2023-09-07 21:23 UTC, maxim-trokhimtchouk approved these changes

2023-09-07 21:24 UTC, merged